import { Product, ServiceType } from './types';

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'n-1',
    name: 'Netflix Premium 4K',
    description: 'Ultra HD streaming on 4 devices simultaneously. No ads.',
    price: 4.99,
    originalPrice: 22.99,
    duration: '1 Month',
    type: ServiceType.NETFLIX,
    features: ['4K Ultra HD', '4 Screens', 'Download content', 'No Ads'],
    image: 'https://images.unsplash.com/photo-1574375927938-d5a98e8efe30?q=80&w=800&auto=format&fit=crop',
    popular: true,
    stock: 50,
  },
  {
    id: 'n-12',
    name: 'Netflix Premium 1 Year',
    description: 'Best value. 12 months of 4K streaming.',
    price: 49.99,
    originalPrice: 275.00,
    duration: '12 Months',
    type: ServiceType.NETFLIX,
    features: ['4K Ultra HD', '4 Screens', 'Shared Account', 'Warranty'],
    image: 'https://images.unsplash.com/photo-1522869635100-1f4906a1759f?q=80&w=800&auto=format&fit=crop',
    stock: 20,
  },
  {
    id: 'd-1',
    name: 'Disney+ Premium',
    description: 'Access to Disney, Pixar, Marvel, Star Wars, and National Geographic.',
    price: 2.99,
    originalPrice: 13.99,
    duration: '1 Month',
    type: ServiceType.DISNEY,
    features: ['IMAX Enhanced', '4K UHD & HDR', '4 Screens', 'GroupWatch'],
    image: 'https://images.unsplash.com/photo-1620176662758-c0b852d4e84e?q=80&w=800&auto=format&fit=crop',
    stock: 100,
  },
  {
    id: 'c-1',
    name: 'Crunchyroll Mega Fan',
    description: 'The world\'s largest anime collection. Watch new episodes 1 hour after Japan.',
    price: 1.99,
    originalPrice: 9.99,
    duration: '1 Month',
    type: ServiceType.CRUNCHYROLL,
    features: ['No Ads', 'Offline Viewing', '4 Devices', 'Simulcast'],
    image: 'https://images.unsplash.com/photo-1541562232579-512a21360020?q=80&w=800&auto=format&fit=crop',
    stock: 35,
  },
  {
    id: 'b-1',
    name: 'Ultimate Stream Bundle',
    description: 'Get everything. Netflix, Disney+, and Crunchyroll for one low price.',
    price: 8.99,
    originalPrice: 45.99,
    duration: '1 Month',
    type: ServiceType.BUNDLE,
    features: ['All 3 Services', 'Premium/Mega Fan', 'Instant Delivery', '24/7 Support'],
    image: 'https://images.unsplash.com/photo-1593784991095-a20506948430?q=80&w=800&auto=format&fit=crop',
    popular: true,
    stock: 10,
  },
];

export const SERVICE_COLORS = {
  [ServiceType.NETFLIX]: 'yellow',
  [ServiceType.DISNEY]: 'yellow',
  [ServiceType.CRUNCHYROLL]: 'yellow',
  [ServiceType.BUNDLE]: 'yellow',
  [ServiceType.KEY]: 'yellow',
  [ServiceType.ACCOUNT]: 'yellow',
  [ServiceType.SERVICE]: 'yellow',
  [ServiceType.OTHER]: 'yellow',
};
